@startuml Logout (GET)

header Sameple Massage Shop Sequence Diagram
footer Page %page% of %lastpage%
title "Logout (GET)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:logout" as routerLogout
participant "<<controllers>>\n:logout" as controllersLogout
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:user" as UserDatabase

client->server ++:req.get('/logout')
server->routerLogout ++:app.use('/logout',auth)
routerLogout -> controllersLogout ++:logout()
routerLogout <-- controllersLogout --:response clear cookies
server <-- routerLogout --:response clear cookies
client <-- server --:response clear cookies

@enduml